name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        
    - name: Setup Firefox and GeckoDriver
      uses: browser-actions/setup-firefox@v1
      
    - name: Setup GeckoDriver
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ github.token }}
        
    - name: Run tests
      run: |
        # Add geckodriver to PATH
        export PATH="$PATH:/usr/local/bin"
        # Check Firefox and geckodriver versions 
        firefox --version
        geckodriver --version
        # Run tests with verbose output
        pytest tests/ -v --browser=firefox
        
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: |
          reports/
          screenshots/
