name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/google.gpg > /dev/null
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get -y install google-chrome-stable
        
    - name: Setup Chrome and ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        # Optional: specify a Chrome version
        chromedriver-version: 'latest'
        
    - name: Run tests
      run: |
        # Add ChromeDriver to PATH
        export PATH="$PATH:/usr/local/bin"
        # Check Chrome and ChromeDriver versions 
        google-chrome --version
        chromedriver --version
        # Run tests with verbose output
        pytest tests/ -v --browser=chrome
        
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: |
          reports/
          screenshots/
